let usersarr: string[] =["admin","eric","john","smith","peter"];
console.log(usersarr.push('susan'));
let scores: Array<number> = [10,20,30,40,50];
console.log(scores.length);
console.log(scores[6]);
console.log(scores.push(90));
console.log(scores.splice(2,2,100));
console.log(scores);
console.log(usersarr.pop());
console.log(usersarr);
console.log(usersarr.shift());
console.log(usersarr.unshift('rav4'));
console.log(usersarr);
console.log(usersarr.filter((user) => user.startsWith('peter')));
console.log(usersarr.includes('john'));
console.log(scores.indexOf(100,0));
console.log(scores);
console.log(usersarr.map((user) => user.toUpperCase()));
console.log(usersarr.find((user) => (user)=== 'john'));
usersarr.forEach((user) => console.log(user));